from typing import Callable, Any, ParamSpecArgs, ParamSpecKwargs

def eagain_errcode(func: Callable, poller_func: Callable, *args: ParamSpecArgs, **kwargs: ParamSpecKwargs) -> Any: ...
def eagain_write_errcode(write_func: Callable, poller_func: Callable, data: bytes) -> None: ...
