# This file is part of ssh2-python.
# Copyright (C) 2017-2025 Panos Kittenis
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation, version 2.1.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

from typing import Tuple, Generator

class SFTPAttributes:
    @property
    def flags(self) -> int: ...
    @flags.setter
    def flags(self, flags: int): ...
    @property
    def filesize(self) -> int: ...
    @filesize.setter
    def filesize(self, filesize: int): ...
    @property
    def uid(self) -> int: ...
    @uid.setter
    def uid(self, uid: int): ...
    @property
    def gid(self) -> int: ...
    @gid.setter
    def gid(self, gid: int): ...
    @property
    def permissions(self) -> int: ...
    @permissions.setter
    def permissions(self, permissions: int): ...
    @property
    def atime(self) -> int: ...
    @atime.setter
    def atime(self, atime: int): ...
    @property
    def mtime(self) -> int: ...
    @mtime.setter
    def mtime(self, mtime: int): ...

class SFTPHandle:
    def __next__(self) -> Tuple[int, bytes]: ...
    def close(self) -> int: ...
    def read(self, buffer_maxlen: int) -> Tuple[int, bytes]: ...
    def readdir_ex(self, longentry_maxlen: int=1024,
                   buffer_maxlen: int=1024) -> Generator[Tuple[int, bytes, bytes, SFTPAttributes]]: ...
    def readdir(self, buffer_maxlen:int =1024) -> Generator[Tuple[int, bytes, SFTPAttributes]]: ...
    def write(self, buf: bytes) -> Tuple[int, bytes]: ...
    def fsync(self) -> int: ...
    def seek(self, offset: int) -> None: ...
    def seek64(self, offset: int) -> None: ...
    def rewind(self) -> None: ...
    def tell64(self) -> int: ...
    def fstat_ex(self, attrs: SFTPAttributes, setstat: int) -> int: ...
    def fstat(self) -> SFTPAttributes:...
    def fsetstat(self, attrs: SFTPAttributes) -> int: ...
    def fstatvfs(self) -> SFTPStatVFS: ...


class SFTPStatVFS:
    @property
    def f_bsize(self) -> int: ...
    @property
    def f_frsize(self) -> int: ...
    @property
    def f_blocks(self) -> int: ...
    @property
    def f_bfree(self) -> int: ...
    @property
    def f_bavail(self) -> int: ...
    @property
    def f_files(self) -> int: ...
    @property
    def f_ffree(self) -> int: ...
    @property
    def f_favail(self) -> int: ...
    @property
    def f_fsid(self) -> int: ...
    @property
    def f_flag(self) -> int: ...
    @property
    def f_namemax(self) -> int: ...
