class SFTPAttributes:
    @property
    def flags(self) -> int: ...
    @flags.setter
    def flags(self, flags: int): ...
    @property
    def filesize(self) -> int: ...
    @filesize.setter
    def filesize(self, filesize: int): ...
    @property
    def uid(self) -> int: ...
    @uid.setter
    def uid(self, uid: int): ...
    @property
    def gid(self) -> int: ...

    @gid.setter
    def gid(self, gid: int): ...
    @property
    def permissions(self) -> int: ...
    @permissions.setter
    def permissions(self, permissions: int): ...
    @property
    def atime(self) -> int: ...
    @atime.setter
    def atime(self, atime: int): ...
    @property
    def mtime(self) -> int: ...
    @mtime.setter
    def mtime(self, mtime: int): ...
