from typing import Final, AnyStr

LIBSSH2_SFTP_S_IFMT: Final[int] = ...
LIBSSH2_SFTP_S_IFIFO: Final[int] = ...
LIBSSH2_SFTP_S_IFCHR: Final[int] = ...
LIBSSH2_SFTP_S_IFDIR: Final[int] = ...
LIBSSH2_SFTP_S_IFBLK: Final[int] = ...
LIBSSH2_SFTP_S_IFREG: Final[int] = ...
LIBSSH2_SFTP_S_IFLNK: Final[int] = ...
LIBSSH2_SFTP_S_IFSOCK: Final[int] = ...
LIBSSH2_SFTP_ATTR_SIZE: Final[int] = ...
LIBSSH2_SFTP_ATTR_UIDGID: Final[int] = ...
LIBSSH2_SFTP_ATTR_PERMISSIONS: Final[int] = ...
LIBSSH2_SFTP_ATTR_ACMODTIME: Final[int] = ...
LIBSSH2_SFTP_ATTR_EXTENDED: Final[int] = ...
LIBSSH2_FXF_READ: Final[int] = ...
LIBSSH2_FXF_WRITE: Final[int] = ...
LIBSSH2_FXF_APPEND: Final[int] = ...
LIBSSH2_FXF_CREAT: Final[int] = ...
LIBSSH2_FXF_TRUNC: Final[int] = ...
LIBSSH2_FXF_EXCL: Final[int] = ...
LIBSSH2_SFTP_S_IRWXU: Final[int] = ...
LIBSSH2_SFTP_S_IRUSR: Final[int] = ...
LIBSSH2_SFTP_S_IWUSR: Final[int] = ...
LIBSSH2_SFTP_S_IXUSR: Final[int] = ...
LIBSSH2_SFTP_S_IRWXG: Final[int] = ...
LIBSSH2_SFTP_S_IRGRP: Final[int] = ...
LIBSSH2_SFTP_S_IWGRP: Final[int] = ...
LIBSSH2_SFTP_S_IXGRP: Final[int] = ...
LIBSSH2_SFTP_S_IRWXO: Final[int] = ...
LIBSSH2_SFTP_S_IROTH: Final[int] = ...
LIBSSH2_SFTP_S_IWOTH: Final[int] = ...
LIBSSH2_SFTP_S_IXOTH: Final[int] = ...
LIBSSH2_SFTP_ST_RDONLY: Final[int] = ...
LIBSSH2_SFTP_ST_NOSUID: Final[int] = ...

class SFTP:
    def get_channel(self): ...
    def open_ex(self, filename: bytes, filename_len: int, flags: int, mode: int, open_type: int): ...
    def open(self, filename: AnyStr, flags: int, mode: int): ...
    def opendir(self, path: AnyStr): ...
    def rename_ex(self, source_filename: bytes, source_filename_len: int, dest_filename: bytes, dest_filename_len: int, flags: int): ...
    def rename(self, source_filename: AnyStr, dest_filename: AnyStr): ...
    def unlink(self, filename: AnyStr): ...
    def statvfs(self, path: AnyStr): ...
    def mkdir(self, path: AnyStr, mode: int): ...
    def rmdir(self, path: AnyStr): ...
    def stat(self, path: AnyStr): ...
    def lstat(self, path: AnyStr): ...
    # def setstat(self, path, attrs: SFTPAttributes): ...
    def symlink(self, path: AnyStr, target: AnyStr): ...
    def realpath(self, path: AnyStr, max_len: int = 256): ...
    def last_error(self): ...
