from typing import BinaryIO, Iterable, Generator, Tuple

from ssh2.session import Session

def find_eol(buf: bytes, pos: int) -> Tuple[int, int]: ...
def readline(buf: Iterable[bytes]) -> Generator[bytes]: ...
def version(required_version: int = 0) -> str: ...
def ssh2_exit() -> None: ...
def wait_socket(_socket: BinaryIO, session: Session, timeout: int=1) -> None: ...
def handle_error_codes(errcode: int) -> int: ...
