from typing import Iterable, Generator, Tuple

from ssh2.session import Session

def find_eol(buf: bytes, pos: int) -> Tuple[int, int]: ...
def readline(buf: Iterable) -> Generator: ...
def version(required_version: int = 0) -> str: ...
def ssh2_exit() -> None: ...
def wait_socket(_socket, session: Session, timeout=1) -> None: ...
def handle_error_codes(errcode: int) -> int: ...
